---
abstract: "It's new $module"
author:
  - 'catatsuy <catatsuy@catatsuy.org>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-2zicon
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Acme::2zicon:
    file: lib/Acme/2zicon.pm
    version: '0.1'
  Acme::2zicon::Base:
    file: lib/Acme/2zicon/Base.pm
    version: '0.1'
  Acme::2zicon::KinoshitaHiyori:
    file: lib/Acme/2zicon/KinoshitaHiyori.pm
    version: '0.1'
  Acme::2zicon::MatobaKarin:
    file: lib/Acme/2zicon/MatobaKarin.pm
    version: '0.1'
  Acme::2zicon::NagataMinari:
    file: lib/Acme/2zicon/NagataMinari.pm
    version: '0.1'
  Acme::2zicon::NakamuraAkari:
    file: lib/Acme/2zicon/NakamuraAkari.pm
    version: '0.1'
  Acme::2zicon::NemotoNagi:
    file: lib/Acme/2zicon/NemotoNagi.pm
    version: '0.1'
  Acme::2zicon::NishiNanami:
    file: lib/Acme/2zicon/NishiNanami.pm
    version: '0.1'
  Acme::2zicon::OkumuraNonoka:
    file: lib/Acme/2zicon/OkumuraNonoka.pm
    version: '0.1'
  Acme::2zicon::ShigematsuYuka:
    file: lib/Acme/2zicon/ShigematsuYuka.pm
    version: '0.1'
  Acme::2zicon::SuyamaEmiri:
    file: lib/Acme/2zicon/SuyamaEmiri.pm
    version: '0.1'
  Acme::2zicon::YoshimuraNana:
    file: lib/Acme/2zicon/YoshimuraNana.pm
    version: '0.1'
requires:
  Class::Accessor: '0'
  DateTime: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/catatsuy/acme-2zicon/issues
  homepage: https://github.com/catatsuy/acme-2zicon
  repository: git://github.com/catatsuy/acme-2zicon.git
version: '0.1'
x_authority: cpan:CATATSUY
